### ISSUE TITLE
Private Packagist

### ISSUE THREAD

**Issue by rommelfreddy** [badges/poser#23]
is it possible to use the private packagist.com instead of the public packagist.org?

**Comment by jmleroux** [comment]
Hello @Fredwak ,
I don't fully understand the question. Do you mean using private composer for `composer require` command?
Anyway, I never used the private packagist but I would think it works with all public packages.

**Comment by Fredwak** [comment]
Hi,

 

the problem is, that our packages are private. 

The private Packagist ist exactly the same service like packagist.org. With the different that the packages can be private.

 

I want to use the badges in our Confluence, but the Poser can not access to the private Packagist.

 

Is there a way to realize that the Poser access to the private Packagist with an token?

 

Best Regards

Freddy

**Comment by jmleroux** [comment]
How do you use this repo?
Just a composer dependency or something else like the command line interface?

**Comment by Fredwak** [comment]
Yes i am using composer to install the my dependencies.
But i have disabled the default public packagist and enable the private Packagist.

`{
    "repositories": [
        {"type": "composer", "url": "https://repo.packagist.com/COMPANY/"},
        {"packagist.org": false}
    ]
}`

**Comment by jmleroux** [comment]
Then it would require some kind of synchronization with the public packagist. I don't know about private packagist, but I used Satis and ToranProxy some times ago. They were able to synchronize packagist on a private server and you could then require from them instead of public internet.
IMHO, it's more an issue with how private and public packagist are working.
Why did you disable `packagist.org`? It's just for pulling dependencies and it will not make your code public.

**Comment by JellyBellyDev** [comment]
Badge Poser fetches public information from packagist.org and github.com using the appropriate sdk via token.
It would not be able to get information from private repo!
